# Generated by Django 4.2.4 on 2023-09-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorModel',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
    ]
